name: Sync AUR packages

on:
  schedule:
    - cron: '17 6,14,22 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      profile:
        description: 'Profile to build'
        type: choice
        options:
          - all
          - generic
          - alderlake
          - tremont
          - znver5
        default: all

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ matrix.profile }}
      cancel-in-progress: false
    strategy:
      fail-fast: false
      matrix:
        profile: ${{ (inputs.profile == 'all' || !inputs.profile) && fromJSON('["generic", "alderlake", "tremont", "znver5"]') || fromJSON(format('["{0}"]', inputs.profile)) }}

    steps:
      - uses: actions/checkout@v6

      - name: Cleanup pre-installed tools
        shell: bash
        run: |
          shopt -s nullglob
          sudo rm -rf /usr/share/{dotnet,swift,az*,gradle*,*conda} \
            /opt/{ghc,az} \
            /usr/local/share/boost /usr/local/graalvm /usr/local/julia* "$AGENT_TOOLSDIRECTORY"

      - uses: karin0/auv@main
        with:
          release_tag: ${{ matrix.profile }}
          repo_name: aur-${{ matrix.profile }}
          packages_file: profiles/${{ matrix.profile }}/packages.txt
          makepkg_conf_file: profiles/${{ matrix.profile }}/makepkg.conf
          patches_dir: patches
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
